version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      # - $(aws ecr get-login --no-include-email --region us-west-2)
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 962804699607.dkr.ecr.us-west-2.amazonaws.com
 
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t aws-innovators-repo:latest .
      - docker tag aws-innovators-repo:latest 962804699607.dkr.ecr.us-west-2.amazonaws.com/aws-innovators-repo:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 962804699607.dkr.ecr.us-west-2.amazonaws.com/aws-innovators-repo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"<container name>","imageUri":"<ECR repository URI>:latest"}]' > imagedefinitions.json
    artifacts:
      files: imagedefinitions.json
